version: '3.8'

services:

  jenkins:
    user: root
    # Image officielle Jenkins (LTS = Long Term Support)
    image: jenkins/jenkins:lts
    ports:
      # Port d'accès web de Jenkins (http://localhost:8080)
      - "8080:8080"
      # Port d’agent Jenkins (connexion à distance des agents)
      - "50000:50000"
    volumes:
      # Volume persistant pour garder les jobs et la config entre les redémarrages
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

volumes:
  jenkins_home:
