version: '3.8'

services:
  elasticsearch:
    # Utilise l'image officielle d'Elasticsearch version 7.17.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      # Configure Elasticsearch en mode noeud unique (utile pour le dev)
      - discovery.type=single-node
      # Désactive la sécurité (authentification, SSL) pour simplifier l'accès en local
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    # Interface graphique pour explorer les données stockées dans Elasticsearch
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    # Utilisé pour lire, transformer et envoyer les données vers Elasticsearch
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      # - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # - ./pipeline:/usr/share/logstash/pipeline
            - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - ../data/network_security_logs.csv:/usr/share/logstash/network_security_logs.csv
    ports:
      - "5044:5044"
      - "5045:5045"  
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    # Réseau virtuel interne entre Elasticsearch, Logstash et Kibana
    driver: bridge