name: CI-CD ELK SmartCity

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vérification du fichier docker-compose
        run: docker-compose -f elk/docker-compose.yml config

      - name: Construction des services
        run: docker-compose -f elk/docker-compose.yml build